### PR TITLE
Moving the shib_auth module into the contrib sub folder

### PR DESCRIPTION
**Pull request by joelpittet**

### CODE REVIEW

**Comment by joelpittet** [comment]
@ubcfos/owners Can someone on this list merge in my change? Still working out how to add people to the pull request convo at create time on github;)  🐙

**Comment by ghost** [comment]
I'm getting a 404 at https://github.com/orgs/ubcfos/teams/owners

--Carlin

**Comment by grandmasterv** [comment]
@joelpittet You are an owner now and should be able to merge this request yourself correct?

**Comment by joelpittet** [comment]
I'm a owner and can merge myself, just wanted not give special rules for myself and get a second pair of eyeballs on my commits.

**Pull request merged**
